# Generated by Django 5.0.3 on 2024-03-16 17:30

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Produto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("codigo", models.CharField(max_length=50, unique=True)),
                ("nome", models.CharField(max_length=100)),
                ("altura", models.DecimalField(decimal_places=2, max_digits=5)),
                ("largura", models.DecimalField(decimal_places=2, max_digits=5)),
                ("profundidade", models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
    ]
