# Generated by Django 5.0.3 on 2024-03-16 20:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cadastro_produtos", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="produto",
            name="altura",
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name="produto",
            name="largura",
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name="produto",
            name="profundidade",
            field=models.FloatField(),
        ),
        migrations.CreateModel(
            name="Comentario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("texto", models.TextField()),
                (
                    "produto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comentarios",
                        to="cadastro_produtos.produto",
                    ),
                ),
            ],
        ),
    ]
